version: "3.7"
services:
  reverse_proxy:
    image: nginx
    container_name: reverse_proxi
    volumes:
      - type: bind
        source: ./nginx-default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./nginx-proxy.conf
        target: /etc/nginx/includes/proxy.conf
      - type: bind
        source: ./error.html
        target: /var/www/html/error.html
    networks:
      - network_A
      - network_B
    ports:
      - 80:80
    depends_on:
      - "server_a"
      - "server_b"

  server_a:
    image: nginx
    container_name: server_a
    volumes:
      - type: bind
        source: ./server-a.html
        target: /usr/share/nginx/html/index.html
      - type: bind
        source: ./a.png
        target: /usr/share/nginx/html/a.jpg
    networks:
      - network_A
    ports:
      - "80"

  server_b:
    image: nginx
    container_name: server_b
    volumes:
      - type: bind
        source: ./server-b.html
        target: /usr/share/nginx/html/index.html
      - type: bind
        source: ./b.jpg
        target: /usr/share/nginx/html/b.jpg
    networks:
      - network_B
    ports:
      - "80"

networks:
  network_A:
  network_B:
